import { Poppins, Roboto} from "next/font/google"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const myfont = Poppins({
  subsets: ["latin"],
  weight: ["100" , "300" ,"700"]
})


const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: ":Hachathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={myfont.className}>
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
